apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: VA-Notify
  links:
    - url: https://www.google.com/
      title: VA Notify Full Documentation
      icon: dashboard
  annotations:
    github.com/project-slug: chriscdm/VA-Notify
    backstage.io/techdocs-ref: dir:.
  description: Provides notification services via a REST API and a web application where teams can create / manage notification templates as needed; supports email, text, push notifications, and onsite notifications2; does not store any veteran information
  tags:
    - utility
    - comms
spec:
  type: utility
  lifecycle: production
  owner: test_user
  system: examples
